version: 2.1

jobs:
  check:
    docker:
      - image: circleci/python:3.7.3-stretch

    steps:
      - checkout

      - run:
          name: Install tox
          command: |
            python3 -m venv venv	
            source venv/bin/activate
            pip install tox

      - run:
          name: Run linters
          command: |
            . venv/bin/activate
            tox -e flake8,mypy

workflows:
  check-code:
    jobs:
      - check
