name: lint

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [lint]
